---
- name: Configure Windows desktops
  #become: yes
  hosts: windows_desktops
  #vars:
    #ansible_connection: ssh
    #ansible_ssh_user: student
    #ansible_ssh_pass: "P@ssw0rd"
  tasks:
    - name: Ensure local admin user exists for each desktop
      win_user:
        name: "{{ item }}"
        password: "WGU123"
        groups:
          - Administrators
        state: present
        update_password: on_create
      loop:
        - DesktopUser1
        - DesktopUser2
        - DesktopUser3
        - DesktopUser4

- name: Configure Linux test boxes in ACCT_Network
  become: yes 
  hosts: test_boxes_acct
  remote_user: student
  tasks:
    - name: Ensure TestUser1 exists on ACCT_Network test boxes
      user:
        name: "TestUser1"
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        group: sudo
        state: present

- name: Configure Linux test boxes in MGMT_Network
  become: yes
  hosts: test_boxes_mgmt
  remote_user: student
  tasks:
    - name: Ensure TestUser2 exists on MGMT_Network test boxes
      user:
        name: "TestUser2"
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        group: sudo
        state: present
